import * as sync from './sync.js';
import { localDate, localIso, mergeDocumentActivity } from './journal-record.js';
const HOSTNAME = globalThis.location?.hostname || '';
const ENABLED = 'quill.journalEnabled.v1'; const ACTIVITY = 'quill.journalActivity.v1'; const REPO = {
  owner: HOSTNAME.endsWith('.github.io')
    ? HOSTNAME.slice(0, -'.github.io'.length)
    : '',
  repo: 'webapp-data', branch: 'main'
};
let clientPromise = null; let lastState = { status: 'not reported', pendingCount: 0, errorCode: '' };
const read = key => { try { return localStorage.getItem(key) || ''; } catch { return ''; } }; const write = (key, value) => { try { localStorage.setItem(key, value); } catch {} };
const parse = value => { try { const parsed = JSON.parse(value); return parsed && typeof parsed === 'object' ? parsed : {}; } catch { return {}; } };
export const isJournalEnabled = () => read(ENABLED) === '1'; export const getJournalState = () => ({ enabled: isJournalEnabled(), ...lastState });
function normalizeActivityLedger(rows) { if (!Array.isArray(rows)) throw new Error('Invalid Quill Journal activity ledger.'); const items = {}; for (const record of rows) { if (!record || record.kind !== 'file-activity' || typeof record.id !== 'string' || !record.data?.itemId || !Array.isArray(record.data?.actions)) throw new Error('Invalid Quill Journal activity ledger record.'); const date = localDate(record.at); items[`${date}:${record.data.itemId}`] = record; } return items; }
function pruneActivityLedger(items) { const cutoff = Date.now() - 90 * 86400000; Object.keys(items).forEach(id => { if (Date.parse(items[id].data?.lastAt || items[id].updatedAt) < cutoff) delete items[id]; }); return items; }
export function validateActivityLedger(rows) { return Object.values(normalizeActivityLedger(rows)); }
export function exportActivityLedger() { return Object.values(parse(read(ACTIVITY))); }
export function replaceActivityLedger(rows, { merge = false } = {}) { const next = normalizeActivityLedger(rows); const items = merge ? { ...parse(read(ACTIVITY)), ...next } : next; pruneActivityLedger(items); write(ACTIVITY, JSON.stringify(items)); return Object.values(items); }
export function clearActivityLedger() { try { localStorage.removeItem(ACTIVITY); return true; } catch { return false; } }
async function client() { if (clientPromise) return clientPromise; clientPromise = (async () => { const context = sync.getContextId(); if (!context) return null; const v2 = await import('../../shared/v2/journal.js'); return v2.createJournalClient({ app: 'quill', context, namespace: 'quill-journal', isEnabled: isJournalEnabled, resolveConfig: async () => { const token = sync.getToken(); if (!token) throw Object.assign(new Error('Journal authentication unavailable'), { code: 'AUTH' }); return { ...REPO, token }; }, onState: state => { lastState = { ...lastState, status: state.status, pendingCount: state.pendingCount, errorCode: state.errorCode || '' }; } }); })().catch(() => null); return clientPromise; }
export async function toggleJournal(enabled, name = '') { if (enabled) { if (!sync.getToken()) return { ok: false, reason: 'token' }; try { if (!sync.getContextId()) await sync.ensureContext(name); if (name) sync.setContextLabel(name); } catch { return { ok: false, reason: 'context' }; } } write(ENABLED, enabled ? '1' : '0'); clientPromise = null; lastState = { ...lastState, status: enabled ? 'ready' : 'disabled', errorCode: '' }; const reported = await reportStatus(); if (enabled && !reported) return { ok: false, reason: 'status' }; return { ok: true }; }
export async function reportStatus(extra = {}) { const c = await client(); if (!c) return false; try { await c.reportStatus({ journalEnabled: isJournalEnabled(), ...extra }); return true; } catch { return false; } }
export async function recordActivity(document, action, options = {}) { if (!document?.id) return false; const at = options.at || new Date(); const date = localDate(at); const items = parse(read(ACTIVITY)); const key = `${date}:${document.id}`; const record = mergeDocumentActivity(items[key], document, action, at, options); items[key] = record; pruneActivityLedger(items); write(ACTIVITY, JSON.stringify(items)); if (!isJournalEnabled()) return false; const c = await client(); if (!c) return false; try { await c.enqueue(record, { date }); return true; } catch { return false; } }
export async function refreshJournalState() { const c = await client(); if (c) { try { lastState.pendingCount = await c.pendingCount(); } catch {} } return getJournalState(); }
export function previewBackfill(from, to) { const records = Object.values(parse(read(ACTIVITY))).filter(record => { const date = localDate(record.at); return date >= from && date <= to; }); return { records, dates: new Set(records.map(record => localDate(record.at))).size, historyAccuracy: records.length ? 'exact' : 'future-only' }; }
export async function backfillJournal(from, to) { const preview = previewBackfill(from, to); const c = await client(); if (!c) return { ...preview, written: 0, error: new Error('Journal unavailable') }; await reportStatus({ backfill: { status: 'running', from, to, processedDates: 0, totalDates: preview.dates, updatedAt: localIso() } }); for (const record of preview.records) await c.enqueue({ ...record, data: { ...record.data, importedHistory: true, historyAccuracy: 'exact' } }, { date: localDate(record.at) }); const result = await c.flush(); await reportStatus({ backfill: { status: result.error ? 'partial' : 'complete', from, to, processedDates: result.error ? 0 : preview.dates, totalDates: preview.dates, updatedAt: localIso() } }); return { ...preview, ...result }; }
export { localIso };
